### ISSUE TITLE
Unexpected Token at Build Version 2.2.2

### ISSUE THREAD

**Issue by kaushik1094** [brownieboy/react-bootstrap-slider#56] opened 2019-07-08 16:43 UTC
<h3>Version 2.2.2 is requiring an appropriate loader to build dist/react-bootstrap-slider.js</h3>

![BuildError](https://user-images.githubusercontent.com/23369030/60827337-d2fb5900-a164-11e9-839c-a743d247346c.jpg)

**Comment by brownieboy** [comment] 2019-07-13 09:17
Unable to reproduce.

Sadly, I don't have Bamboo server lying around to try and reproduce whatever it is you're trying to do, even if you'd told me what that was.

**Comment by andreoman** [comment] 2019-08-02 14:49
I have the same issue for the node v.8.11.2, npm v5.6.0:

**Comment by markogresak** [comment] 2019-08-12 11:31
@brownieboy it's the ES2015+ syntax in the dist, e.g. `class`, `const` and similar keywords. I suggest adding preset `es2015`. 

See the example in [Babel REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PQKgBApgzgNglgOwC4FoIIG5gEYCcD2A7lBLmCMAFCVwC2ADvrkmAEoQCGAxiwGYG0wAIlyceQgNw0GTFgAUC9ACoBPetDD98gofUUoka6JOmNmYAMrwAJqU0Dh2fPiRQkuDvRSw4t3CcoIAA8zFi4YDigoNjEkACFnV3dPK187YKR0a2j2biQAOgBhbUYEdBYAb0owMC4ACwguAGsAQQRrABF8DrgoDmwYCGswAF4wAAoASlGAPjAqmpqufAQ3MB8_AFEEfsHRsCQ63vy9fHoofOte3aGwAEIRsaErvoGhk0XalbWuAFdcUTIGAqbY3YZjQ7HWgqVJ-fK9UFvaxTKSfOC8CYbUiIwbTBafMDoiZ3P4A8rAnFDPHVAk1SEXaGw0j5dA3FE0z4AXw5YE5kBgJHmPJqRPGpMBSApOyR1NpdKODJhNmZLzZk1RBO5XJpnKkNOWMjKyB61gAsvhfsgpkLPstVixDhwWBCFRqlt8WFjcC0kO44NhfplomN8Z98uH6SdFFAADTCg7OGBIOD0ABcBwVUbOFyQieT9DAAB9C8IoHUiEIebqecBgF9VvhBvkYPgAObjIRen1-gNB_ZCMAAajAACkLAB5ABy-TcuEQrfRKnGXd9c970BjYAQvxgME3ABZJurqJ9I4zlWQxmVCJYL-NIwh8LZNyue4HoMea3XT5nfvRrE6EBMrgABqHAwL80DsmiGL3pmpznPk9QcAgrYQEWJaRghFx1Ch1iDIUuGoRAsoEnaPxEWhmwYOU-xYdGSGUehxYZsc2H5ER-EQIRKFoW6ixnkqaS4PkKwdshxFCJu6EjHMoZkR6mgcE0EDUbRIbxqeHC4GhSDpvJcpgBg4GQemED5NeYEQRAmmLFqcrVoZElUTRVq8MpqmuUgx60pyPl2SeiyivR2YzsqFi5vQpE_lCQlwmJnbhZFUmQLMNpyuRfAeWpyD7AZBJINpun6bZnzGdZZmlbytmOXKjoFOxWIRWc4zuSpOXefxNR-fx9nysc9SNK07RdD0ryDMi_ncvqJQrOUJoAKr_oB1ryZGf4AZkwFWZBUDQdVM2GuUADqcC7gtCC0BaVrRaxirAZc0DuPgS5TYFG2AdtJkaGM1qyelIqwfGhjqPgGIhYhtCIPcjzCJati8Ig7xgAAZCj8b3kYYN3fk57Cbj0MPE88MQIjZTWAOxa2SDEDY4JD1nMm3wEwgMPE-0pNIxTkw8rd_X3ReM4QEg3Zru-HZQwgKUQwyiD-d1PKisDWPg_BDG0BwQRs3DHNk8jaMYzTdOZnjcIa1rRM6wjXOU4W1MqzjpvMozcDM-b2tCCTevc7zAMCSbcXMiQIurv64tCOb0tq6F5vy9VMETMroOq2xDFuBABaW57us26j6O0pjyeO4HInp5nsPZ9b5O2_bRf04LLvM2XHtezbPOfHzxcPcHoth5kHZl1HqehWXcfTTFAv48HO0QHBw-IeVkFx5Gg3NG0nTdNcSL7dWNKAn4q1fmASgNOsF6dmAKGEgg9CBvkNQn06F_gTAYCEOhZRDPfYDHRAQi7mAaw-AMzoVEGsRAR9DjoQNKUeavhzSWiQNaWgwtyzWHyDyUQSB_iswADxXCwKIXgIwKiPlsGlOeFwyEyS3E-EifJgAzA1NyaauQeAJBcLOFIgsEKqHUMGdKkt0wKDOHw6AFlfi0GwKQOMNRzbCMUGIqhkjpG4FkesTIaYwAiOUEYZRUiZE0kXhABRoi9GiTKOOXgYjxgAG0eQ6KURIgxaiHGKPMdpDwKgrHjEceY7cLj4RQHYAAR1-HAUQ1hJhBNCeEyJNIAC60TeixIiUMdRqokSmN0fwmcfpULqNzI2fM2SnGznnOo5yJjtHuNybwS0XB1GcQIkxUp5j6kIEaTSJqkU2l1IaeoiI0jdxDGwCoPp4i5pWJsfYz4fjcnlIKW4sxuTPEcG8bwXxtTxGLNbO3MASTKC72CKEQBpMOA7hYGw-IiQuH0GAhIIAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-3&prettier=false&targets=&version=7.5.5&externalPlugins=).

**Comment by brownieboy** [comment] 2020-01-25 05:00
Closed by version 2.2.3 just published to npmjs.

I fixed it by adding @babel/present-env to my .babelrc, and setting the browserslist to included IE 11.

(Apologies for not noticing @markogresak 's PR, which appears to have done the same thing!)

**Closed by brownieboy** 2020-01-25 05:00 UTC
Labels: Cannot reproduce, More information required
